### ISSUE TITLE
Slow startup times

### ISSUE THREAD

**Issue by garyLockyer** [logstash-plugins/logstash-filter-metrics#32]
Enabling the metrics plugin significantly slows logstash start up time.

Is there a reason for using SecureRandom to generate the random_key_preffix, other than the need for it to be unique across instances?

**Comment by garyLockyer** [comment]
Some timings.
Current master branch:

real	4m54.074s
user	1m0.386s
sys	0m2.378s

real	4m50.860s
user	0m57.401s
sys	0m2.382s

real	6m26.487s
user	1m0.337s
sys	0m2.292s



Updated metrics:
Changed 
   @random_key_preffix = SecureRandom.hex
TO
  @random_key_preffix = Random.new.bytes(16).unpack("H*")[0]


real	1m7.392s
user	0m59.459s
sys	0m2.215s

real	1m5.829s
user	0m57.809s
sys	0m2.036s

real	1m4.236s
user	0m57.002s
sys	0m2.041s

**Comment by jordansissel** [comment]
@garyLockyer Your data gives me two concerns:

1) SecureRandom.hex is probably slow because your system is exhausted of entropy. You'll want to fix that problem.

2) Logstash taking 1 minute to start up in the "faster" case is ... extremely slow. 

What hardware/system is this on? Both start times are extremely slow and unexpected.

**Comment by garyLockyer** [comment]
It's a very old and slow server, that we're using in our dev environment.  We're also running multiple metrics filters.

Fixing the entropy ( installed havegd) brought the start up times down to 1min34s

Which given the nature of the hardware is acceptable.

**Comment by suyograo** [comment]
@garyLockyer ok, closing this now
